name: Compile project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-homekit-mqtt-bridge:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./homekit-mqtt-bridge

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
      
  build-yeelight-controller:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./yeelight-controller

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
